name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4
    - name: Configurazione Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Installazione dipendenze Android
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libsqlite3-dev libffi-dev xclip libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev flip2d autoconf automake libtool pkg-config
        pip3 install --user --upgrade buildozer cython virtualenv
    - name: Compilazione APK con Buildozer
      run: |
        export PATH=$PATH:$HOME/.local/bin
        buildozer android debug
    - name: Carica l'APK finale su GitHub
      uses: actions/upload-artifact@v4
      with:
        name: Gioco-Universo-Infinito-APK
        path: bin/*.apk
